version: '3'
services:
  proxy:
    image: library/nginx:alpine
    container_name: oa-rdepot-proxy
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./docker/proxy/logs/:/var/log/nginx/
      - repository:/opt/rdepot/repo/:ro
    ports:
      - ${RDEPOT_PORT}:80
    depends_on:
      - app
      - repo
    networks:
      - oa-rdepot
  db:
    image: library/postgres:alpine
    restart: always
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/db/rdepot.sql:/docker-entrypoint-initdb.d/rdepot.sql:ro
    networks:
      - oa-rdepot
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  app:
          #build: ./docker/build/app
    image: openanalytics/rdepot-app
    restart: always
    hostname: oa-rdepot-app
    container_name: oa-rdepot-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./docker/app/repository/:/opt/rdepot/generated/
    ports:
      - 8001:8001
    networks:
      - oa-rdepot
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/postgres
      - DB_USERNAME=postgres
      - JAVA_OPTS
  repo:
          #build: ./docker/build/repo
    image: openanalytics/rdepot-repo
    restart: always
    hostname: oa-rdepot-repo
    container_name: oa-rdepot-repo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/repo/oa-rdepot-repo.jar:/opt/repo/oa-rdepot-repo.jar:ro
      - repository:/opt/rdepot/
    networks:
      - oa-rdepot
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:
